package com.redis.om.spring.client;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;

import org.junit.jupiter.api.Test;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

class RedisOmSpringPublicationMetadataTest {

  private static final String JEDIS_GROUP = "redis.clients";
  private static final String JEDIS_MODULE = "jedis";
  private static final String JEDIS_VERSION_PROPERTY = "redisOmSpring.jedisVersion";
  private static final String MODULE_METADATA_PROPERTY = "redisOmSpring.moduleMetadata";

  @Test
  void generatedGradleMetadataPublishesJedisAsMinimumVersionRange() throws IOException {
    Path moduleMetadata = moduleMetadataPath();
    String jedisVersion = jedisVersion();
    String expectedStrictRange = "[%s,)".formatted(jedisVersion);

    assertThat(moduleMetadata)
        .as("Gradle metadata generated by :redis-om-spring:generateMetadataFileForMavenJavaPublication")
        .exists()
        .isRegularFile();
    assertThat(jedisVersion).as("jedisVersion in gradle.properties").isNotBlank();

    JsonNode metadata = new ObjectMapper().readTree(moduleMetadata.toFile());
    List<JedisConstraint> jedisConstraints = findJedisConstraints(metadata);

    assertThat(jedisConstraints)
        .as("Jedis dependency entries in %s", moduleMetadata)
        .extracting(JedisConstraint::variant)
        .containsExactlyInAnyOrder("apiElements", "runtimeElements");

    assertThat(jedisConstraints)
        .as("Jedis should allow newer Boot-managed versions such as 7.4.1")
        .allSatisfy(constraint -> assertThat(constraint.strictly())
            .as("%s Jedis strictly constraint", constraint.variant())
            .isEqualTo(expectedStrictRange));
  }

  private static List<JedisConstraint> findJedisConstraints(JsonNode metadata) {
    List<JedisConstraint> constraints = new ArrayList<>();

    for (JsonNode variant : metadata.path("variants")) {
      for (JsonNode dependency : variant.path("dependencies")) {
        if (isJedisDependency(dependency)) {
          constraints.add(new JedisConstraint(
              variant.path("name").asText(),
              dependency.path("version").path("strictly").asText(null)
          ));
        }
      }
    }

    return constraints;
  }

  private static boolean isJedisDependency(JsonNode dependency) {
    return JEDIS_GROUP.equals(dependency.path("group").asText()) && JEDIS_MODULE.equals(dependency.path("module").asText());
  }

  private static Path moduleMetadataPath() {
    String configuredPath = System.getProperty(MODULE_METADATA_PROPERTY);
    if (configuredPath != null && !configuredPath.isBlank()) {
      return Path.of(configuredPath);
    }

    return projectRoot().resolve("redis-om-spring/build/publications/mavenJava/module.json");
  }

  private static String jedisVersion() throws IOException {
    String configuredVersion = System.getProperty(JEDIS_VERSION_PROPERTY);
    if (configuredVersion != null && !configuredVersion.isBlank()) {
      return configuredVersion;
    }

    Properties properties = new Properties();
    try (InputStream input = Files.newInputStream(projectRoot().resolve("gradle.properties"))) {
      properties.load(input);
    }
    return properties.getProperty("jedisVersion");
  }

  private static Path projectRoot() {
    Path current = Path.of("").toAbsolutePath();
    while (current != null) {
      if (Files.exists(current.resolve("settings.gradle"))) {
        return current;
      }
      current = current.getParent();
    }
    throw new IllegalStateException("Could not locate project root from current working directory.");
  }

  private record JedisConstraint(String variant, String strictly) {
  }
}
