
package com.redis.om.spring.tuple.getter;

/**
 * Specialization of {@link TupleGetter} that always returns the 16th element.
 * <p>
 * Generated by com.speedment.sources.pattern.tuple.TupleGetterPattern
 *
 * @param <T>   the type of the tuple to get a value from
 * @param <T16> the type of the element to return
 *

 *
 */
@FunctionalInterface
public interface TupleGetter16<T, T16> extends TupleGetter<T, T16> {

    @Override
    default int index() {
        return 16;
    }
}