
package com.redis.om.spring.tuple.getter;

/**
 * Specialization of {@link TupleGetter} that always returns the 20th element.
 * <p>
 * Generated by com.speedment.sources.pattern.tuple.TupleGetterPattern
 *
 * @param <T>   the type of the tuple to get a value from
 * @param <T20> the type of the element to return
 *

 *
 */
@FunctionalInterface
public interface TupleGetter20<T, T20> extends TupleGetter<T, T20> {

    @Override
    default int index() {
        return 20;
    }
}