
package com.redis.om.spring.tuple.getter;

/**
 * Specialization of {@link TupleGetter} that always returns the 7th element.
 * <p>
 * Generated by com.speedment.sources.pattern.tuple.TupleGetterPattern
 *
 * @param <T>  the type of the tuple to get a value from
 * @param <T7> the type of the element to return
 *

 *
 */
@FunctionalInterface
public interface TupleGetter7<T, T7> extends TupleGetter<T, T7> {

    @Override
    default int index() {
        return 7;
    }
}