
package com.redis.om.spring.tuple.getter;

/**
 * Specialization of {@link TupleGetter} that always returns the 0th element.
 * <p>
 * Generated by com.speedment.sources.pattern.tuple.TupleGetterPattern
 *
 * @param <T>  the type of the tuple to get a value from
 * @param <T0> the type of the element to return
 *

 *
 */
@FunctionalInterface
public interface TupleGetter0<T, T0> extends TupleGetter<T, T0> {

    @Override
    default int index() {
        return 0;
    }
}