
package com.redis.om.spring.tuple.getter;

/**
 * Specialization of {@link TupleGetter} that always returns the 9th element.
 * <p>
 * Generated by com.speedment.sources.pattern.tuple.TupleGetterPattern
 *
 * @param <T>  the type of the tuple to get a value from
 * @param <T9> the type of the element to return
 *

 *
 */
@FunctionalInterface
public interface TupleGetter9<T, T9> extends TupleGetter<T, T9> {

    @Override
    default int index() {
        return 9;
    }
}