
package com.redis.om.spring.tuple.getter;

/**
 * Specialization of {@link TupleGetter} that always returns the 10th element.
 * <p>
 * Generated by com.speedment.sources.pattern.tuple.TupleGetterPattern
 *
 * @param <T>   the type of the tuple to get a value from
 * @param <T10> the type of the element to return
 *

 *
 */
@FunctionalInterface
public interface TupleGetter10<T, T10> extends TupleGetter<T, T10> {

    @Override
    default int index() {
        return 10;
    }
}