
package com.redis.om.spring.tuple.getter;

/**
 * Specialization of {@link TupleGetter} that always returns the 5th element.
 * <p>
 * Generated by com.speedment.sources.pattern.tuple.TupleGetterPattern
 *
 * @param <T>  the type of the tuple to get a value from
 * @param <T5> the type of the element to return
 *

 *
 */
@FunctionalInterface
public interface TupleGetter5<T, T5> extends TupleGetter<T, T5> {

    @Override
    default int index() {
        return 5;
    }
}