
package com.redis.om.spring.tuple.getter;

/**
 * Specialization of {@link TupleGetter} that always returns the 12nd element.
 * <p>
 * Generated by com.speedment.sources.pattern.tuple.TupleGetterPattern
 *
 * @param <T>   the type of the tuple to get a value from
 * @param <T12> the type of the element to return
 *

 *
 */
@FunctionalInterface
public interface TupleGetter12<T, T12> extends TupleGetter<T, T12> {

    @Override
    default int index() {
        return 12;
    }
}