
package com.redis.om.spring.tuple.getter;

/**
 * Specialization of {@link TupleGetter} that always returns the 2nd element.
 * <p>
 * Generated by com.speedment.sources.pattern.tuple.TupleGetterPattern
 *
 * @param <T>  the type of the tuple to get a value from
 * @param <T2> the type of the element to return
 *

 *
 */
@FunctionalInterface
public interface TupleGetter2<T, T2> extends TupleGetter<T, T2> {

    @Override
    default int index() {
        return 2;
    }
}