
package com.redis.om.spring.tuple.getter;

/**
 * Specialization of {@link TupleGetter} that always returns the 14th element.
 * <p>
 * Generated by com.speedment.sources.pattern.tuple.TupleGetterPattern
 *
 * @param <T>   the type of the tuple to get a value from
 * @param <T14> the type of the element to return
 *

 *
 */
@FunctionalInterface
public interface TupleGetter14<T, T14> extends TupleGetter<T, T14> {

    @Override
    default int index() {
        return 14;
    }
}