
package com.redis.om.spring.tuple.getter;

/**
 * Specialization of {@link TupleGetter} that always returns the 13rd element.
 * <p>
 * Generated by com.speedment.sources.pattern.tuple.TupleGetterPattern
 *
 * @param <T>   the type of the tuple to get a value from
 * @param <T13> the type of the element to return
 *

 *
 */
@FunctionalInterface
public interface TupleGetter13<T, T13> extends TupleGetter<T, T13> {

    @Override
    default int index() {
        return 13;
    }
}