
package com.redis.om.spring.tuple.getter;

/**
 * Specialization of {@link TupleGetter} that always returns the 6th element.
 * <p>
 * Generated by com.speedment.sources.pattern.tuple.TupleGetterPattern
 *
 * @param <T>  the type of the tuple to get a value from
 * @param <T6> the type of the element to return
 *

 *
 */
@FunctionalInterface
public interface TupleGetter6<T, T6> extends TupleGetter<T, T6> {

    @Override
    default int index() {
        return 6;
    }
}