
package com.redis.om.spring.tuple.getter;

/**
 * Specialization of {@link TupleGetter} that always returns the 17th element.
 * <p>
 * Generated by com.speedment.sources.pattern.tuple.TupleGetterPattern
 *
 * @param <T>   the type of the tuple to get a value from
 * @param <T17> the type of the element to return
 *

 *
 */
@FunctionalInterface
public interface TupleGetter17<T, T17> extends TupleGetter<T, T17> {

    @Override
    default int index() {
        return 17;
    }
}