
package com.redis.om.spring.tuple.getter;

/**
 * Specialization of {@link TupleGetter} that always returns the 4th element.
 * <p>
 * Generated by com.speedment.sources.pattern.tuple.TupleGetterPattern
 *
 * @param <T>  the type of the tuple to get a value from
 * @param <T4> the type of the element to return
 *

 *
 */
@FunctionalInterface
public interface TupleGetter4<T, T4> extends TupleGetter<T, T4> {

    @Override
    default int index() {
        return 4;
    }
}