site:
  title: Redis OM Spring Documentation
  url: https://redis.github.io/redis-om-spring
  start_page: redis-om-spring::index.adoc

content:
  sources:
    # Current version (from current branch only)
    - url: ..
      branches: HEAD
      start_path: docs/content

runtime:
  fetch: true
  cache_dir: ./.cache/antora

ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.16/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    toc: ~
    xrefstyle: short