
package com.redis.om.spring.tuple.impl;

import com.redis.om.spring.tuple.Tuple;
import com.redis.om.spring.tuple.AbstractTuple;
import com.redis.om.spring.tuple.EmptyTuple;

/**
 * An implementation class of a {@link EmptyTuple}.
 * <p>
 * Generated by com.speedment.sources.pattern.tuple.TupleImplPattern
 */
public final class Tuple0Impl
extends AbstractTuple
implements EmptyTuple {

    public static final EmptyTuple EMPTY_TUPLE = new Tuple0Impl();

    /**
     * Constructs a {@link Tuple} of type {@link EmptyTuple}.
     */
    private Tuple0Impl() {
        super(Tuple0Impl.class);
    }
}