
package com.redis.om.spring.tuple.impl;

import com.redis.om.spring.tuple.Tuple;
import com.redis.om.spring.tuple.AbstractTuple;
import com.redis.om.spring.tuple.Pair;

/**
 * An implementation class of a {@link Pair}.
 * <p>
 * Generated by com.speedment.sources.pattern.tuple.TupleImplPattern
 *
 * @param <T0> type of element 0
 * @param <T1> type of element 1
 */
public final class Tuple2Impl<T0, T1>
extends AbstractTuple
implements Pair<T0, T1> {

    /**
     * Constructs a {@link Tuple} of type {@link Pair}.
     *
     * @param e0 element 0
     * @param e1 element 1
     */
    public Tuple2Impl(T0 e0, T1 e1) {
        super(Tuple2Impl.class, e0, e1);
    }

    @SuppressWarnings("unchecked")
    @Override
    public T0 getFirst() {
        return ((T0) values[0]);
    }

    @SuppressWarnings("unchecked")
    @Override
    public T1 getSecond() {
        return ((T1) values[1]);
    }
}