
package com.redis.om.spring.tuple.impl;

import com.redis.om.spring.tuple.Tuple;
import com.redis.om.spring.tuple.AbstractTuple;
import com.redis.om.spring.tuple.Single;

/**
 * An implementation class of a {@link Single}.
 * <p>
 * Generated by com.speedment.sources.pattern.tuple.TupleImplPattern
 *
 * @param <T0> type of element 0
 */
public final class Tuple1Impl<T0>
extends AbstractTuple
implements Single<T0> {

    /**
     * Constructs a {@link Tuple} of type {@link Single}.
     *
     * @param e0 element 0
     */
    public Tuple1Impl(T0 e0) {
        super(Tuple1Impl.class, e0);
    }

    @SuppressWarnings("unchecked")
    @Override
    public T0 get0() {
        return ((T0) values[0]);
    }
}