
package com.redis.om.spring.tuple.impl;

import com.redis.om.spring.tuple.Tuple;
import com.redis.om.spring.tuple.AbstractTuple;
import com.redis.om.spring.tuple.Hextuple;

/**
 * An implementation class of a {@link Hextuple}.
 * <p>
 * Generated by com.speedment.sources.pattern.tuple.TupleImplPattern
 *
 * @param <T0> type of element 0
 * @param <T1> type of element 1
 * @param <T2> type of element 2
 * @param <T3> type of element 3
 * @param <T4> type of element 4
 * @param <T5> type of element 5
 */
public final class Tuple6Impl<T0, T1, T2, T3, T4, T5>
extends AbstractTuple
implements Hextuple<T0, T1, T2, T3, T4, T5> {

    /**
     * Constructs a {@link Tuple} of type {@link Hextuple}.
     *
     * @param e0 element 0
     * @param e1 element 1
     * @param e2 element 2
     * @param e3 element 3
     * @param e4 element 4
     * @param e5 element 5
     */
    public Tuple6Impl(
            T0 e0,
            T1 e1,
            T2 e2,
            T3 e3,
            T4 e4,
            T5 e5) {
        super(Tuple6Impl.class, e0, e1, e2, e3, e4, e5);
    }

    @SuppressWarnings("unchecked")
    @Override
    public T0 get0() {
        return ((T0) values[0]);
    }

    @SuppressWarnings("unchecked")
    @Override
    public T1 get1() {
        return ((T1) values[1]);
    }

    @SuppressWarnings("unchecked")
    @Override
    public T2 get2() {
        return ((T2) values[2]);
    }

    @SuppressWarnings("unchecked")
    @Override
    public T3 get3() {
        return ((T3) values[3]);
    }

    @SuppressWarnings("unchecked")
    @Override
    public T4 get4() {
        return ((T4) values[4]);
    }

    @SuppressWarnings("unchecked")
    @Override
    public T5 get5() {
        return ((T5) values[5]);
    }
}