name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from tag
        id: get_version
        run: |
          realversion="${GITHUB_REF/refs\/tags\//}"
          realversion="${realversion//v/}"
          echo "VERSION=$realversion" >> "$GITHUB_OUTPUT"

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
          cache: maven

      - name: Update Maven version
        run: mvn versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }}

      # Build all modules with the 'publication' profile
      - name: Build project
        run: mvn -Ppublication clean package -DskipTests

      # Stage only the artifacts we want to publish (not the parent POM)
      - name: Stage artifacts
        run: |
          # Create staging directory
          mkdir -p target/staging-deploy
          
          # Create a local Maven repository structure just for our modules
          # redis-om-spring module
          mkdir -p target/staging-deploy/com/redis/om/redis-om-spring/${{ steps.get_version.outputs.VERSION }}
          cp redis-om-spring/target/redis-om-spring-${{ steps.get_version.outputs.VERSION }}.jar \
             target/staging-deploy/com/redis/om/redis-om-spring/${{ steps.get_version.outputs.VERSION }}/
          cp redis-om-spring/target/redis-om-spring-${{ steps.get_version.outputs.VERSION }}-sources.jar \
             target/staging-deploy/com/redis/om/redis-om-spring/${{ steps.get_version.outputs.VERSION }}/
          cp redis-om-spring/target/redis-om-spring-${{ steps.get_version.outputs.VERSION }}-javadoc.jar \
             target/staging-deploy/com/redis/om/redis-om-spring/${{ steps.get_version.outputs.VERSION }}/
          cp redis-om-spring/pom.xml \
             target/staging-deploy/com/redis/om/redis-om-spring/${{ steps.get_version.outputs.VERSION }}/redis-om-spring-${{ steps.get_version.outputs.VERSION }}.pom
          
          # redis-om-spring-ai module
          mkdir -p target/staging-deploy/com/redis/om/redis-om-spring-ai/${{ steps.get_version.outputs.VERSION }}
          cp redis-om-spring-ai/target/redis-om-spring-ai-${{ steps.get_version.outputs.VERSION }}.jar \
             target/staging-deploy/com/redis/om/redis-om-spring-ai/${{ steps.get_version.outputs.VERSION }}/
          cp redis-om-spring-ai/target/redis-om-spring-ai-${{ steps.get_version.outputs.VERSION }}-sources.jar \
             target/staging-deploy/com/redis/om/redis-om-spring-ai/${{ steps.get_version.outputs.VERSION }}/
          cp redis-om-spring-ai/target/redis-om-spring-ai-${{ steps.get_version.outputs.VERSION }}-javadoc.jar \
             target/staging-deploy/com/redis/om/redis-om-spring-ai/${{ steps.get_version.outputs.VERSION }}/
          cp redis-om-spring-ai/pom.xml \
             target/staging-deploy/com/redis/om/redis-om-spring-ai/${{ steps.get_version.outputs.VERSION }}/redis-om-spring-ai-${{ steps.get_version.outputs.VERSION }}.pom
          
          # List staged artifacts for verification
          echo "Staged artifacts:"
          find target/staging-deploy -type f | sort

      # Deploy with JReleaser which handles signing and publishing to Maven Central
      - name: Release with JReleaser
        uses: jreleaser/release-action@v2
        with:
          arguments: full-release
          version: latest
        env:
          # JReleaser project configuration
          JRELEASER_PROJECT_VERSION: ${{ steps.get_version.outputs.VERSION }}
          
          # GitHub authentication
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
          JRELEASER_GITHUB_USERNAME: ${{ secrets.GIT_USER }}
          
          # GPG signing configuration
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          JRELEASER_SIGNING_ENABLED: true
          JRELEASER_SIGNING_ACTIVE: ALWAYS
          
          # Maven Central publishing configuration
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          
          # Debug mode for more verbose output
          JRELEASER_DEBUG: true

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jreleaser-output
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties