
package com.redis.om.spring.tuple.impl.mapper;

import com.redis.om.spring.tuple.AbstractTupleMapper;
import com.redis.om.spring.tuple.EmptyTuple;
import com.redis.om.spring.tuple.TupleMapper;
import com.redis.om.spring.tuple.Tuples;

/**
 * An implementation class of a {@link TupleMapper } of degree 0
 * <p>
 * Generated by com.speedment.sources.pattern.tuple.TupleMapperImplPattern
 *
 * @param <T> Type of the original object for the mapper to use when creating a
 *            {@code Tuple }
 */
public final class Tuple0MapperImpl<T>
extends AbstractTupleMapper<T, EmptyTuple>
implements TupleMapper<T, EmptyTuple> {

    public static final Tuple0MapperImpl<?> EMPTY_MAPPER = new Tuple0MapperImpl<>();

    /**
     * Constructs a {@link TupleMapper } that can create {@link EmptyTuple }.
     */
    private Tuple0MapperImpl() {
        super(0);
    }

    @Override
    public EmptyTuple apply(T t) {
        return Tuples.of(

        );
    }
}